# Generated by Django 2.2.4 on 2019-10-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsad',
            options={'ordering': ['-created_time'], 'verbose_name': '新闻广告', 'verbose_name_plural': '新闻广告'},
        ),
        migrations.AlterModelTable(
            name='newsad',
            table='news_ad',
        ),
    ]
